### ISSUE TITLE
Added space

### ISSUE THREAD

**Issue by arifd11** [WaxMoon/MultiAppDemo#3]
Intent always null when start activity with new space, how to added space?

**Comment by WaxMoon** [comment]
plz update opensdk git module and try again

APP_INSTALL_USER(https://github.com/WaxMoon/MultiAppDemo/blob/main/app/src/main/java/org/waxmoon/ma/ApkEnv.java )

**Comment by arifd11** [comment]
Yes, its my fault, i fix it 5 hour ago
